n = 150;
% Initialize progress bar with optinal parameters:
upd = textprogressbar2(n, 'barlength', 10, ...
                         'updatestep', 10, ...
                         'startmsg', 'Waiting... ',...
                         'endmsg', ' Finally!', ...
                         'showbar', true, ...
                         'showremtime', false, ...
                         'showactualnum', true, ...
                         'barsymbol', '+', ...
                         'emptybarsymbol', '-');
for i = 1:n
   pause(0.05);
   upd(i);
end
